Update launcher version and test new fd framework
flathub/com.albiononline.AlbionOnline pull request #49
Opened 2024-01-29 06:46 UTC by sajw12

2024-01-29 07:47 UTC, sajw12 commented
I think this successfully build and installs downloads the latest launcher using fd23.08 but the launcher can't download the actual game properly. The error I get is "Error on download - downloaded file has wrong size". Using the executable installer from the Albion website works fine, i.e I do not have this error.

This is the same problem I was having with this Flatpak as built in the main branch with 21.x.

2024-01-29 10:48 UTC, AsciiWolf requested changes

2024-01-29 10:48 UTC, AsciiWolf commented on com.albiononline.AlbionOnline.appdata.xml
> +      <image type="source">https://cdn.cloudflare.steamstatic.com/steam/apps/761890/ss_ace9036fa9be3f15a81ebeb64c5843ec79b72be4.jpg?t=1704713171</image>
```suggestion
      <image type="source">https://cdn.cloudflare.steamstatic.com/steam/apps/761890/ss_ace9036fa9be3f15a81ebeb64c5843ec79b72be4.jpg</image>
```

2024-01-29 10:48 UTC, AsciiWolf commented on com.albiononline.AlbionOnline.appdata.xml
> +      <image type="source">https://cdn.cloudflare.steamstatic.com/steam/apps/761890/ss_c197aa77b6f65af34fd51292e9033da6960ee23f.jpg?t=1704713171</image>
```suggestion
      <image type="source">https://cdn.cloudflare.steamstatic.com/steam/apps/761890/ss_c197aa77b6f65af34fd51292e9033da6960ee23f.jpg</image>
```

2024-01-29 10:52 UTC, AsciiWolf commented
I sadly do not have push rights to this repo. Anyway, it is great that this Flatpak is finally being updated to a recent fd runtime. :-) Thanks a lot for working on this!

2024-02-22 12:36 UTC, AsciiWolf commented
bot, build

2024-02-22 15:07 UTC, barthalion commented
The appdata file is just completely broken right now. Please validate it with appstreamcli locally to see all errors.

2025-02-08 22:46 UTC, sajw12 commented
bot, build

2025-02-08 23:30 UTC, sajw12 commented
bot, build

2026-01-02 21:31 UTC, closed without merging